// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package myipv1alpha1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MyipServiceClient is the client API for MyipService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MyipServiceClient interface {
	// public IP履歴作成, Role: IBPF
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	// public IP 履歴取得, Role, MyH, Biz
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
}

type myipServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMyipServiceClient(cc grpc.ClientConnInterface) MyipServiceClient {
	return &myipServiceClient{cc}
}

func (c *myipServiceClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/myip.v1alpha1.MyipService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *myipServiceClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/myip.v1alpha1.MyipService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MyipServiceServer is the server API for MyipService service.
// All implementations should embed UnimplementedMyipServiceServer
// for forward compatibility
type MyipServiceServer interface {
	// public IP履歴作成, Role: IBPF
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	// public IP 履歴取得, Role, MyH, Biz
	Get(context.Context, *GetRequest) (*GetResponse, error)
}

// UnimplementedMyipServiceServer should be embedded to have forward compatible implementations.
type UnimplementedMyipServiceServer struct {
}

func (UnimplementedMyipServiceServer) Create(context.Context, *CreateRequest) (*CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedMyipServiceServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}

// UnsafeMyipServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MyipServiceServer will
// result in compilation errors.
type UnsafeMyipServiceServer interface {
	mustEmbedUnimplementedMyipServiceServer()
}

func RegisterMyipServiceServer(s grpc.ServiceRegistrar, srv MyipServiceServer) {
	s.RegisterService(&MyipService_ServiceDesc, srv)
}

func _MyipService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyipServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/myip.v1alpha1.MyipService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyipServiceServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MyipService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyipServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/myip.v1alpha1.MyipService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyipServiceServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MyipService_ServiceDesc is the grpc.ServiceDesc for MyipService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MyipService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "myip.v1alpha1.MyipService",
	HandlerType: (*MyipServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _MyipService_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _MyipService_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "myip/v1alpha1/api.proto",
}
